name: rust-egui

on:
  push:
    branches: [ "egui" ]
  pull_request:
    branches: [ "egui" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build egui
      run: cd egui-mpi2p && cargo build --verbose
    - name: Run egui tests
      run: cd egui-mpi2p && cargo test --verbose
